Unleash/yggdrasil

- .github/workflows/sarif-and-test.yaml
Adds a workflow running Clippy analysis and `cargo test`
> chore: add sarif (clippy) and test workflow

- java-sdk/java-glue/src/lib.rs
- node-sdk/src/lib.rs
- python-sdk/src/lib.rs
- unleash-yggdrasil/README.md
- unleash-yggdrasil/src/lib.rs
- unleash-yggdrasil/src/strategy_parsing.rs
- unleash-yggdrasil/src/strategy_upgrade.rs
Minor refactoring and renaming to remove (or disable non relevant) warnings in Clippy
> Make clippy happy

- unleash-yggdrasil/src/state.rs
Adds some robustness to the context property parsing code. This will now handle cases where the properties object coming from JSON serialisation or FFI layers that use the same have a defined but null field in the context object
> add robustness handling to context property parsing

- java-sdk/java-glue/src/lib.rs
- node-sdk/src/lib.rs
- python-sdk/src/lib.rs
- unleash-yggdrasil/Cargo.toml
- unleash-yggdrasil/benches/benchmark.rs
- unleash-yggdrasil/src/lib.rs
Adds a utility method to resolve all features
> feat: add resolve all features method

- .envrc
- .gitignore
- devenv.lock
- devenv.nix
- devenv.yaml
This change adds a basic devenv setup to this project.
> meta: add devenv

- java-engine/build.gradle
- java-engine/src/main/java/io/getunleash/engine/IsEnabledResponse.java
- java-engine/src/main/java/io/getunleash/engine/StatusCode.java
- java-engine/src/main/java/io/getunleash/engine/TakeStateResponse.java
- java-engine/src/main/java/io/getunleash/engine/UnleashEngine.java
- java-engine/src/main/java/io/getunleash/engine/VariantDef.java
- java-engine/src/main/java/io/getunleash/engine/VariantResponse.java
- java-engine/src/main/java/io/getunleash/engine/YggResponse.java
- java-engine/src/main/java/io/getunleash/engine/YggdrasilInvalidInputException.java
- java-engine/src/main/java/io/getunleash/engine/YggdrasilParseException.java
- java-engine/src/test/java/io/getunleash/engine/UnleashEngineTest.java
Adapt Java Engine to latest changes in Yggdrasil and make tests pass the specification
> chore: make Java Engine pass specs

- .github/workflows/build-java.yaml
- .github/workflows/sarif-and-test.yaml
- java-engine/build.gradle
- java-engine/src/main/java/io/getunleash/engine/UnleashEngine.java
- java-engine/src/main/java/io/getunleash/engine/YggdrasilFFI.java
- java-engine/src/test/java/io/getunleash/engine/UnleashEngineTest.java
- java-engine/src/test/java/io/getunleash/engine/YggdrasilFFITest.java
Autoclosable implementation and some tests.
Automated testing with GH Actions
References:
1. https://inside.java/2022/05/27/testing-clean-cleaner-cleanup/
2. https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ref/Cleaner.html
> chore: implement memory clean up

- .github/workflows/build-java.yaml
- .github/workflows/sarif-and-test.yaml
- .gitignore
- README.md
- unleash-yggdrasil/src/lib.rs
- unleash-yggdrasil/src/strategy_parsing.rs
- unleash-yggdrasil/src/strategy_upgrade.rs
1. Variants will be hashed with new seed
2. Fixed a [bug](https://github.com/Unleash/yggdrasil/issues/60), where variant strategy evaluation was not using groupId from strategy
> feat: new hashing implemented for variants

- dotnet-engine/README.md
- dotnet-engine/Yggdrasil.Engine/Yggdrasil.Engine.csproj
Adds nuget package info to csproj and updates the readme
> feat: set up nuget package info in csproj and update readme

- .github/workflows/build-dotnet.yaml
Adds a build workflow for building dotnet PRs
> feat: first implementation of build workflow

- java-engine/src/main/java/io/getunleash/engine/UnleashEngine.java
Make some changes in UnleashEngine internals to release memory properly
> chore(java): improve memory usage

- .github/workflows/build-dotnet.yaml
- README.md
- dotnet-engine/Yggdrasil.Engine.Tests/CustomStrategyReturningTrue.cs
- dotnet-engine/Yggdrasil.Engine.Tests/YggdrasilEngineTest.cs
- dotnet-engine/Yggdrasil.Engine/FFI.cs
- dotnet-engine/Yggdrasil.Engine/Strategies.cs
- dotnet-engine/Yggdrasil.Engine/Types.cs
- dotnet-engine/Yggdrasil.Engine/YggdrasilEngine.cs
Seems like my formatter disagrees with some of the current formatting. I think it's probably right, since this feels more consistent to me.
> style: formatting

- .github/workflows/build-dotnet.yaml
- dotnet-engine/Yggdrasil.Engine.Tests/CustomStrategyReturningTrue.cs
- dotnet-engine/Yggdrasil.Engine.Tests/YggdrasilEngineTest.cs
- dotnet-engine/Yggdrasil.Engine/FFI.cs
- dotnet-engine/Yggdrasil.Engine/Strategies.cs
- dotnet-engine/Yggdrasil.Engine/Types.cs
- dotnet-engine/Yggdrasil.Engine/YggdrasilEngine.cs
Apply formatting, put in a standard, be done with this
> chore(dotnet): standardize formatting on dotnet format

- .github/workflows/build-java.yaml
- java-engine/build.gradle.kts
- java-engine/src/main/java/io/getunleash/engine/CustomStrategiesEvaluator.java
- java-engine/src/main/java/io/getunleash/engine/UnleashEngine.java
- java-engine/src/main/java/io/getunleash/engine/YggdrasilFFI.java
- java-engine/src/test/java/io/getunleash/engine/CustomStrategiesEvaluatorTest.java
- java-engine/src/test/java/io/getunleash/engine/UnleashEngineTest.java
- java-engine/src/test/java/io/getunleash/engine/YggdrasilFFITest.java
This adds Java 8 target to be able to import the engine in Java 8 projects
> chore(java): java 8 support

- java-engine/build.gradle.kts
- java-engine/src/main/java/io/getunleash/engine/CustomStrategiesEvaluator.java
- java-engine/src/main/java/io/getunleash/engine/UnleashEngine.java
- java-engine/src/test/java/io/getunleash/engine/UnleashEngineTest.java
After doing a first integration in Java SDK these are feature that were missing in the Engine
> chore(java): handling of fallback strategy

- .github/workflows/add-to-project.yml
Adds project workflow dispatch
> chore: add project workflow

- dotnet-engine/Yggdrasil.Engine/Yggdrasil.Engine.csproj
Not planning on changing the API in the near future so we can mark this as stable now
> chore: stable release for dotnet engine

- python-engine/tests/test_engine.py
- python-engine/yggdrasil_engine/engine.py
Simple pass through to Ygg to list the features known to the engine at call time
> feat(python): add function to list known features

- java-engine/src/main/resources/META-INF/native-image/io.getunleash/yggdrasil-engine/proxy-config.json
- java-engine/src/main/resources/META-INF/native-image/io.getunleash/yggdrasil-engine/reflect-config.json
- java-engine/src/main/resources/META-INF/native-image/io.getunleash/yggdrasil-engine/resource-config.json
Adds Graal metadata to all types detected in this test https://github.com/iromu/spring-boot-openfeature/tree/main/examples/unleash-advanced 
The same metadata was included in the example to test it ( https://github.com/iromu/spring-boot-openfeature/tree/main/examples/unleash-advanced/src/main/resources/META-INF/native-image/io.getunleash/yggdrasil-engine )
To validate the change, you can use the above example and compile a native executable on local, win/mac/linux:
- https://github.com/iromu/spring-boot-openfeature/blob/main/examples/native.ps1
- https://github.com/iromu/spring-boot-openfeature/blob/main/examples/native.sh
Closes #215
> #215 Added Graal metadata

- .github/workflows/build-wasm.yaml
- .github/workflows/sarif-and-test.yaml
- test-data/delta_patch.json
- unleash-yggdrasil/Cargo.toml
- unleash-yggdrasil/src/lib.rs
Also bump client-spec to 5.2.2
> chore: bump types to 0.15.9

- unleash-yggdrasil/Cargo.toml
Bumps unleash-types from 0.15.9 to 0.15.11
> chore: bump unleash-types to 0.15.11

- java-engine/src/main/java/io/getunleash/engine/UnleashEngine.java
- java-engine/src/test/java/io/getunleash/engine/UnleashEngineTest.java
Makes the pointer code a little easier to grok and a little harder to break by wrapping it in its own functions
> chore: refactor resolving pointers to objects on the java side

- flat-buffer-defs/enabled-message.fbs
- java-engine/src/main/java/messaging/Variant.java
- pure-wasm/src/enabled-message_generated.rs
- pure-wasm/src/lib.rs
- pure-wasm/src/serialisation.rs
Adds some reasonable error handling to the WASM layer for the methods for checking enabled and variants
> fix: implement some proper error handling for bad context values

- python-engine/pyproject.toml
- python-engine/tox.ini
- python-engine/yggdrasil_engine/__init__.py
- python-engine/yggdrasil_engine/custom_strategy.py
Upgrades the message handling in the Python engine to handle the new streaming protocol message format. No new tests because this is already well covered by the client specifications.
> feat(python): implement streaming message handling

- unleash-yggdrasil/src/lib.rs
- unleash-yggdrasil/src/strategy_parsing.rs
> chore: apply Clippy

- .github/workflows/release-plz.yml
- release-plz.toml
Adds a release plz workflow so we can free ourselves from cargo smart-release
> chore: add release plz workflow
