Unleash/yggdrasil

.github/workflows/sarif-and-test.yaml

There might be a much better way of doing this. I'm open to suggestions. But ultimately, we need to resolve the client spec before we run tests

add in a fetch for the client spec in the gh workflow

---

.github/workflows/sarif-and-test.yaml

We've struggled with buildtimes for our rust-actions. After finding the rust-cache action it seems like we've managed to cache enough of the target folder that we no longer have to build all our dependencies each time we make changes to our own code.
This PR switches this project's workflow to use rust-cache as well

ci: update workflow to use rust-cache

---

unleash-yggdrasil/src/strategy_parsing.rs
unleash-yggdrasil/src/strategy_upgrade.rs

User ids can be string types, prior to this, Yggdrasil was trying to upgrade these to numeric rules like so:
`user_in IN [1,2,3]`
This doesn't work when the user supplies a user id which doesn't parse as a numeric. This PR changes this so that the strategy is upgraded to a string type like so:
`user_in IN ["1","2","3"]`

fix: upgrade user id strategy to string types rather than numerics

---

unleash-yggdrasil/src/lib.rs

Handle cases where get_variant is called and variants is Some but empty

fix: handle empty variants

---

unleash-yggdrasil/Cargo.toml
unleash-yggdrasil/benches/benchmark.rs
unleash-yggdrasil/src/lib.rs

Adds basic benchmarks for a sniff test for performance. This isn't a complete analysis of the performance profile, only a rough guide

chore: add basic benchmarks

---

python-sdk/src/lib.rs
unleash-yggdrasil/Cargo.toml
unleash-yggdrasil/src/lib.rs

This adds metrics gathering for the core Yggdrasil client, using atomic primitives behind the scenes, which means this is should still be Send & Sync (yay!). The tradeoff here is that the client won't hold metrics longer than the engine holds the internal state - when passing in a new state for compilation, the engine will return unhandled metrics, that's now the callers responsibility to handle unsent metrics

feat: implement metrics gathering for core

---

java-sdk/java-glue/Cargo.toml
node-sdk/Cargo.toml
python-sdk/Cargo.toml
unleash-yggdrasil/Cargo.toml

Having updated unleash types to 0.10.0 to handle properties as an object map when using it as a query parameter we need yggdrasil to be on the same version.

task: Bump unleash types to 0.10.0

---

unleash-yggdrasil/src/error.rs
unleash-yggdrasil/src/lib.rs

I noticed that `.get_variant()` doesn't work properly - the logic behind stickiness didn't consider `default` as a potential value (which I believe is present for every variant by "default"?). This caused `.resolve_variant()` to return `None`, which resulted in the default disabled variant being returned for the `.get_variant()` calls. 
While trying to fix that I refactored the variant stickiness logic to match the behavior of other SDKs (e.g. node, go) - unless that was intentional? :thinking:
Also fallback random stickiness was using `[0, 100)` range and the total variants weight sums up to 1000, so I believe for it to work properly it should be `[0, total_weight)` instead, right?

fix: fix variant stickiness

---

unleash-yggdrasil/src/lib.rs
unleash-yggdrasil/src/strategy_grammar.pest
unleash-yggdrasil/src/strategy_parsing.rs
unleash-yggdrasil/src/strategy_upgrade.rs

This completely reworks the way that the `default` and `random` keywords are handled by the grammar so they work correctly and remove a bunch of ugly edge cases in the `rollout_constraint`. As a side effect, this allows us to specify much more flexible rules for stickiness.
Firstly because `random` was completely ignored in the strategy upgrade path and that needed to be fixed. This caused the strategy to instead try to use a custom context field called "random" as its stickiness property, which short circuited the entire strategy to false. 
However, the bulk of the changes here are to fix the approach that led to the broken code in the first place. This was caused by incorrectly treating the stickiness property as if it were a special case of a context property. That doesn't model a …

fix: redesigns the way stickiness is handled in the grammar to support default and random

---

unleash-yggdrasil/Cargo.toml
unleash-yggdrasil/src/strategy_grammar.pest
unleash-yggdrasil/src/strategy_parsing.rs
unleash-yggdrasil/src/strategy_upgrade.rs
unleash-yggdrasil/tests/grammar_prop_tests.proptest-regressions
unleash-yggdrasil/tests/grammar_prop_tests.rs

Adds support for arbitrary strings in the grammar by allowing atom escaping of quotation marks within the string rule. For bonus points, we also include escaping of those characters.

fix: support for arbitrary strings

---

unleash-yggdrasil/src/lib.rs

Adds a resolve method for Yggdrasil that can compute a single toggle. This better supports Edge, which currently needs to iterate the whole hashmap to resolve a toggle

feat: add single toggle resolve method

---

unleash-yggdrasil/Cargo.toml

Bump to include update to unleash-types to avoid serializing nulls

chore: updated to new chrono and unleash-types

---

.github/workflows/sarif-and-test.yaml
README.md
node-sdk/Cargo.toml
unleash-yggdrasil/Cargo.toml
unleash-yggdrasil/benches/benchmark.rs
unleash-yggdrasil/src/lib.rs
unleash-yggdrasil/src/strategy_parsing.rs
unleash-yggdrasil/src/strategy_upgrade.rs
unleash-yggdrasil/tests/grammar_prop_tests.rs
yggdrasilffi/Cargo.toml

This adds support for strategy variants, as defined here:  https://github.com/Unleash/client-specification/blob/main/specifications/16-strategy-variants.json 
Metrics will not work against the strategy variants but they're not in use anywhere right now
This works a little differently from how this is likely going to be implemented in other SDKs, since it taps into the Yggdrasil grammar. The flow works like this:
- Compile the strategy to a Vec of Yggdrasil rule fragments, granular to the strategy level
- When a variant is requested, find the first strategy that resolves to true and get the strategy variants for that, reuse the strategy stickiness for that variant stickiness
- If the above is Some and not None, then pass that variant set to the standard variant resolution flow
- Else check …

feat: add support for strategy variants

---

unleash-yggdrasil/Cargo.toml
unleash-yggdrasil/src/lib.rs
yggdrasilffi/src/lib.rs

This makes two major changes to Yggdrasil:
1) Redesigns metrics a little to separate them from the actual compiled toggles. This is mostly for convenience - `CompiledToggle` is arbitrarily clonable, whereas we use Atomic integers for counting metrics, which are not clonable. This allows us to better track toggles and variants that are not defined, without hacking in fake toggles into the cache
2) Exposes a few new lower level constructs to the public API - `check_toggle`, `check_variant`, `count_toggle`, `count_variant` and `get_metrics`. `check_toggle` and `check_variant` are for accessing the toggle state in a way that the caller can determine whether or not the toggle actually exists, which is a hard requirement for some of our SDKs. `count_toggle` and `count_variant` are to allow the …

refactor: better public api for ffi consumers

---

ruby-engine/README.md
ruby-engine/lib/unleash_engine.rb
ruby-engine/spec/unleash_engine_spec.rb
yggdrasilffi/src/lib.rs

This patches the FFI protocol to always return a full and complete JSON response to the caller. This is only handled in Ruby right now so we can spike on the protocol

chore: restructure ffi layer

---

ruby-engine/Gemfile
ruby-engine/Gemfile.lock
ruby-engine/README.md
ruby-engine/lib/unleash_engine.rb
ruby-engine/scripts/mem_check.rb

This fixes the remaining memory leaks in Ruby, where we previously weren't freeing resources we explicitly needed to free. This also adds a script to the ruby engine folder that will exercise the engine with a large number of allocations and do some bare bones checks for obvious leaks 
Co-authored-by: nuno@getunleash.ai

fix: resolves the memory leaks in the ruby ffi layer

---

.gitignore
ruby-engine/Gemfile.lock
ruby-engine/lib/unleash_engine.rb
ruby-engine/unleash-engine.gemspec
yggdrasilffi/src/lib.rs

Attempts to refactor Yggdrasil's FFI layer after reading through the code.
I'm a bit unsure about the method renames. I wanted simpler names on the interface, but also noticed that simpler names sometimes meant unexpected problems.
I tried to be a bit more explicit about the unsafes by making their scope a lot tighter (only unsafe what we need to unsafe). I also updated the docs for the methods and tried to make them consistent. Added some helper methods for a DRY-er approach. Includes some renames, moving some things around and some small typo corrections.
Tests are green, both `cargo test` at the top level and `rspec` in `ruby-engine`.
I hope this makes sense but I'm totally OK with simply discarding this if we don't see value in it 🙂

refactor: Yggdrasil FFI layer

---

unleash-yggdrasil/src/lib.rs

This allows base variants to resolve correctly even when strategy variants are defined as an empty list. Previously, if Yggdrasil found a strategy variant set that was an empty list, it would short circuit to the disabled variant and not fallback to checking the base variants

fix: non strategy variants will work with empty strategy variants

---

.github/workflows/sarif-and-test.yaml
README.md
node-sdk/Cargo.toml
unleash-yggdrasil/Cargo.toml
unleash-yggdrasil/src/lib.rs
yggdrasilffi/Cargo.toml

This PR adds dependent flags to Yggdrasil, complying with the updated client specs.
Regarding these extra points not covered by the spec:
- metrics are not called on dependent features :: this is covered and tested
- impression events are called on dependent features for easier debugging :: yggdrasil doesn't touch impression events 
- warning events for missing dependencies are reported once :: yggdrasil doesn't deal with warnings
@kwasniew , there is a [line in `resolveVariant` in the Node SDK](https://github.com/Unleash/unleash-client-node/blob/6bed4e7f9f1993fc2b6232da8fbbda03cdb3973a/src/client.ts#L238) that checks for parent dependencies being satisfied. What exactly does it do? I tried doing something similar here, but removed it because the tests pass either way. Is this an edge …

feat: add dependent flags

---

unleash-yggdrasil/src/state.rs
unleash-yggdrasil/src/strategy_upgrade.rs

Fixes an issue where Yggdrasil won't assume the current time for a context field, instead it expects the SDKs to send it as part of the context, which they never do.
This patches this to allow Yggdrasil to assume a current time of now if the current time field is not overridden on the context field

fix: allows current time to be assumed when calculating the context

---

devenv.nix

This adds the GitHub CLI as a dependency for nix users, so that we have the tools necessary for the release process.
Ideally, I'd like to add cargo smart-release, too, but it's not available on nixpkgs at the moment.

meta: add GitHub-cli as a dependency in devenv.nix

---

ruby-engine/lib/unleash_engine.rb
ruby-engine/scripts/mem_check.rb
ruby-engine/spec/unleash_engine_spec.rb
ruby-engine/unleash-engine.gemspec

Applies `rubocop --fix` to the Ruby engine

chore: apply rubocop format to Ruby engine

---

unleash-yggdrasil/src/lib.rs
unleash-yggdrasil/src/strategy_parsing.rs

To align it with rest of SDKs, hash result should start from index 1 instead of 0.

refactor: fix normalized hash result to start from 1 instead of 0

---

Cargo.toml

Sets workspace resolver to 2. Workspace v1 is deprecated and the warnings are getting annoying

chore: set workspace resolver to 2 explicitly

---

dotnet-engine/Yggdrasil.Engine.Tests/YggdrasilEngineTest.cs
dotnet-engine/Yggdrasil.Engine/FFILinux.cs
dotnet-engine/Yggdrasil.Engine/FFIMacOS.cs
dotnet-engine/Yggdrasil.Engine/FFIWin.cs
dotnet-engine/Yggdrasil.Engine/IFFIAccess.cs
dotnet-engine/Yggdrasil.Engine/YggdrasilEngine.cs
java-engine/src/main/java/io/getunleash/engine/UnleashEngine.java
java-engine/src/main/java/io/getunleash/engine/YggdrasilFFI.java

This makes the .NET and Java engines run their tests again after the implementation of custom strategies. This does **not** implement custom strategies, just gives us a green build and test

chore: custom strategy placeholder

---

dotnet-engine/Yggdrasil.Engine.Tests/YggdrasilEngineTest.cs
dotnet-engine/Yggdrasil.Engine/FFI.cs
dotnet-engine/Yggdrasil.Engine/YggdrasilEngine.cs
unleash-yggdrasil/src/lib.rs
yggdrasilffi/src/lib.rs

This PR adds support to Yggdrasil for checking whether impression events should be emitted for specified feature toggle.
This PR also adds this capability to the .NET Yggdrasil wrapper
- Lacks unit tests

feat: add shouldemitimpressionevents to yggdrasil and .NET wrapper

---

unleash-yggdrasil/src/strategy_parsing.rs
unleash-yggdrasil/src/strategy_upgrade.rs

This makes the rule upgrader escape incoming string operators if they contain free floating quotes. So this:
`user_id in [" look me Im "cool"  "]`
Should escape to :
`user_id in [" look me Im \"cool\"  "]`
This then gets removed during evaluation phase so that we don't have to escape quotes in the context

fix: make free floating quotes in string operators work correctly

---

.github/workflows/build-dotnet.yaml
.github/workflows/build-java.yaml
.github/workflows/build-wasm.yaml

When Yggdrasil or the FFI changes, build the dependent sub-projects. This will give us a fast feedback loop without having to build them in every PR

chore: build dependents on ygg

---

yggdrasilffi/src/lib.rs

This is to be used in host languages to know if a strategy is implemented inside unleash-yggdrasil or requires a custom strategy implementation on the host language

chore: expose known strategies

---

ruby-engine/README.md
ruby-engine/build.sh
ruby-engine/ext/extconf.rb
ruby-engine/lib/yggdrasil_engine.rb
ruby-engine/scripts/mem_check.rb
ruby-engine/spec/custom_strategy_spec.rb
ruby-engine/spec/yggdrasil_engine_spec.rb
ruby-engine/yggdrasil-engine.gemspec

Big rename of all the ruby implementations from UnleashEngine to Yggdrasil engine, to keep it inline with .NET and our naming strategy

chore: rename everything to Yggrrasil rather than Unleash in ruby engine

---

java-engine/src/main/java/io/getunleash/engine/YggdrasilFFI.java

Fixes the path in MacOS, like mentioned in https://github.com/Unleash/yggdrasil/pull/91#discussion_r1394103945

fix: use absolutepath, fixing path in macos

---

unleash-yggdrasil/benches/benchmark.rs
unleash-yggdrasil/src/lib.rs
unleash-yggdrasil/src/state.rs
unleash-yggdrasil/src/strategy_parsing.rs
yggdrasilffi/src/lib.rs

When taking state, different types of parsing errors can happen. In such situations, Yggdrasil should fail gracefully communicate the error to the client.

feat(yggdrasil): Bubble up errors on take state

---

.github/workflows/sarif-and-test.yaml
unleash-yggdrasil/src/lib.rs
yggdrasilffi/src/lib.rs

This add the enabled status of the toggle to the response in get_variant and does effectively the same logic in the FFI layers. This is a redesign of https://github.com/Unleash/yggdrasil/pull/91, to make the variant handling code a little less invasive and a little safer. This is the important PR since it allows us to do this in Edge.
Notably this does not handle the new property in the `check_variant` method in the core layer of Yggdrasil, instead it makes this the FFI layers problem, which I think is okay, since the FFI code has all the information it needs to be able to determine this. This is encoded in the type signatures of the respective methods so it should be tough to misuse.
Handling code for Java, Ruby and Dotnet is in other PRs to make this easier to review. Patches for the …

feat: add feature enabled property to variant checks 

---

.github/workflows/build-dotnet.yaml
.github/workflows/sarif-and-test.yaml
dotnet-engine/Yggdrasil.Engine.Tests/YggdrasilEngineTest.cs
dotnet-engine/Yggdrasil.Engine/Types.cs
unleash-yggdrasil/src/lib.rs
yggdrasilffi/src/lib.rs

Depends on https://github.com/Unleash/yggdrasil/pull/98
Basically just allows that to propagate out. Shameless stolen from https://github.com/Unleash/yggdrasil/pull/91

feat(dotnet): add variant enabled response

---

unleash-yggdrasil/Cargo.toml
unleash-yggdrasil/src/strategy_grammar.pest
unleash-yggdrasil/src/strategy_parsing.rs
unleash-yggdrasil/src/strategy_upgrade.rs

This adds a hostname strategy implementation for Yggdrasil core.

feat(core): implement hostname strategy in core

---

unleash-yggdrasil/src/strategy_upgrade.rs

This allows the code path that converts raw strategy structs to the DSL format to fallback to "false" when a recoverable error is encountered. Typically this is because no parameters were passed for the strategy. This means the strategies will be ignored when evaluated.
This isn't necessary to pass the spec tests and "should" never happen but life doesn't work like that and we can and should handle recoverable errors.

fix(core): strategies that are broken will now default to false

---

unleash-yggdrasil/src/strategy_parsing.rs
unleash-yggdrasil/src/strategy_upgrade.rs

This fixes a few silly mistakes in the hostname strategy (my bad).
- Hostname strategy should now be generated correctly in the upgrade path, rather than creating a remote address strategy
- Hostname strategy should now completely ignore casing
- Hostname strategy in Rust land should check `hostname` and not `HOSTNAME`

fix(core): hostname strategy should now work correctly

---

dotnet-engine/Yggdrasil.Engine/Yggdrasil.Engine.csproj

Runs the Yggdrasil cargo build --release on dotnet build as a prebuilt step when building as debug (should help local dev)

chore(dotnet): prebuild yggdrasil on Debug build

---

ruby-engine/Gemfile
ruby-engine/Gemfile.lock
ruby-engine/yggdrasil-engine.gemspec

This strips an unnecessary dependency from the Ruby engine that was blocking Yggdrasil from working on JRuby (pretty sure this means Rubinus will work too but we don't guarantee that as a target and I haven't and am not intending to test that). 
Most of the changes here are as a result of tooling setting up the necessary changes to pull the equivalent native interfaces here for the JVM

fix(ruby): works on jruby

---

unleash-yggdrasil/src/lib.rs
unleash-yggdrasil/src/strategy_upgrade.rs

This makes two patches to Yggdrasil's strategy parsing flow:
1) Toggles will no longer affect each other during compilation. Previously, a toggle with an invalid rule would fail the entire response. Now that single toggle will default to false and others will compile correctly.This should be very rare
2) The user id strategy is more tolerant to failure in it's parameters - specifically, it'll escape cases where Unleash would sometimes save and send an incorrect set of parameters
This does have the side effect of preventing major issues in the grammar from bubbling in a meaningful way. Unfortunately, standard logging frameworks do not play nicely with cross compilation to WASM and writing to std out/err can cause problems when done from guest binaries when using FFI. This is fixable, but …

fix: isolate toggle failures

---

unleash-yggdrasil/src/strategy_parsing.rs

There's a common pattern in the rule parser where we need to unpack x number of nodes from the parent into the children nodes, e.g. the hostname constraint, which has 3 children (you can see that from the grammar itself):
`hostname_constraint = { hostname ~ in ~ string_list }`
So we see this:
```
let name = node.next().unwrap();
let operator = node.next().unwrap();
let list = node.next().unwrap();
```
This is safe so long as you know the correct number of nodes and hold to that but this unwrapping pattern is error prone (you need to get exactly the correct number of nodes or risk a panic). 
This PR swaps out this pattern in the code to go through a single function that does this unwrapping, now all those unwraps area together so we can beat them with the `Result` stick.
This gets pattern …

refactor: better handling for unwrapping grammar

---

unleash-yggdrasil/src/strategy_parsing.rs

This builds on the work in #121, to completely eliminate the unwrapping code and replaces it with an error handling pattern that allows non compilable rules to yield an error result rather than panic.
Now any node handling function that could previously panic, will now yield a Result<T, SdkError>

fix: improves edge case handling in rule parsing  

---

unleash-yggdrasil/src/lib.rs
yggdrasilffi/src/lib.rs

Patches take_state to now return a list of warnings of toggles that failed to compile. Take state no longer indicates that it can fail because it can't

chore(core): allow take_state to bubble warnings to caller

---

dotnet-engine/README.md

Add mention of .NET 6.0 runtime for running tests.

docs: dotnet mention .NET 6.0 runtime

---

.github/workflows/build-dotnet.yaml
dotnet-engine/Yggdrasil.Engine/FFI.cs
dotnet-engine/Yggdrasil.Engine/FFIReader.cs
dotnet-engine/Yggdrasil.Engine/NativeLibraryHelper.cs
dotnet-engine/Yggdrasil.Engine/Strategies.cs
dotnet-engine/Yggdrasil.Engine/Types.cs
dotnet-engine/Yggdrasil.Engine/Yggdrasil.Engine.csproj

https://linear.app/unleash/issue/2-2342/change-engine-target-to-net-standard-20
After doing some reading, shouldn't we aim to target [.NET Standard 2.0](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0) instead of .NET 6.0 specifically?
Seems like this has the most compatibility / possible target surface currently.
I needed to make a few changes to make this work, due to missing APIs.
Out of curiosity, is there any specific reason we're targeting .NET 6.0 in our tests? Should we keep it for now?

chore: dotnet target netstandard2

---

unleash-yggdrasil/src/lib.rs
unleash-yggdrasil/src/strategy_parsing.rs
unleash-yggdrasil/src/strategy_upgrade.rs
yggdrasilffi/src/lib.rs

Silly cleanups, mostly trimming out dead code
There's one warning which we now suppress, this one is subtle but important - it allows us to identify custom strategies without treating it as an active edge case (makes the code a bit simpler to have that in place). Wouldn't be a warning if the whole stack was pure Rust but it isn't

chore: warning cleanups

---

dotnet-engine/Yggdrasil.Engine/Types.cs

Part of https://linear.app/unleash/issue/2-1545/yggdrasil-net-integrate-into-unleashclient-net-sdk
By aligning the Variant classes with what our .NET SDK expects we should have a better time integrating it with Yggdrasil and not repeat ourselves.

chore: align dotnet variant classes

---

dotnet-engine/Yggdrasil.Engine.Tests/YggdrasilEngineTest.cs
yggdrasilffi/src/lib.rs

This bubbles slightly better errors in the FFI layer so that the actual error messages are returned rather than the name of the error type. 
Also bubbles the cases where Ygg will receive a broken, uncompilable blob from an external source. Turns out we closed all the known cases where that was possible externally so... bit... hard to test now

feat: better errors in ffi layers

---

dotnet-engine/Yggdrasil.Engine/Types.cs
dotnet-engine/Yggdrasil.Engine/Yggdrasil.Engine.csproj

It seems like, in .NET, constructor argument names are taken into consideration when (de)serializing. This is something we stumbled upon in https://github.com/Unleash/unleash-client-dotnet/pull/224 and something that will probably bite us again later down the line.
It seems like:
- Newtonsoft.Json wants constructor arg names to match the JSON properties;
- System.Text.Json wants the class properties to match the constructor arg names;
This PR makes it so the Variant constructor arg names align with https://github.com/Unleash/unleash-client-dotnet/blob/main/src/Unleash/Internal/Variant.cs#L9 and then adapts the properties to match the new constructor arg names.
This change should hopefully make both serializers happy, since we support both in our .NET SDK.
This should also make it easier …

fix: .NET variant constructor arg names

---

go-engine/go.mod
go-engine/unleash_engine.go
go-engine/unleash_engine_test.go

This updates the FFI implementation of the Go code. This was outdated and was no longer working. I updated the minimum golang to 1.18 in order to use generics.
- I simply use an empty object for the custom strategy (this is also now deprecated in Unleash, right?). This was also done for `getVariant` in Java
- This part (in tests) I copied from a Java test case:
```golang
if variant == nil {
variant = &VariantDef{"disabled", nil, false, engine.IsEnabled("Feature.A", context)}
}
```

feat: make go work with updated FFI

---

.github/workflows/build-wasm.yaml
.github/workflows/sarif-and-test.yaml
unleash-yggdrasil/Cargo.toml
unleash-yggdrasil/src/strategy_parsing.rs
wasm-engine/README.md
wasm-engine/e2e-tests/wasm-engine.test.js
wasm-engine/tests/web.rs

https://linear.app/unleash/issue/2-2630/make-yggdrasil-wasm-build-again
Makes WASM build again by fixing some references and handling `hostname`, since it's not WASM-compatible.
**Question**: We're currently not running tests as part of our actions. Maybe we should?

chore: make wasm build again

---

unleash-yggdrasil/src/strategy_grammar.pest
unleash-yggdrasil/src/strategy_parsing.rs
unleash-yggdrasil/src/strategy_upgrade.rs

This adds a way to parametize random in the grammar so that you can do things like this "random[1000]" which will create an expression of a random number bounded by 0, 1000. Default stickiness and explicitly random flexible rollouts will now use random[10000] instead of random (previously defaulting to 100), which gives random strategies better statistical distribution

fix: makes random distribution better distributed

---

ruby-engine/yggdrasil-engine.gemspec

Just because doing an actual release with a beta dependency feels icky. It's time to let this thing out into the wide world

chore: 0.0.5 of the ruby engine

---

unleash-yggdrasil/Cargo.toml
yggdrasilffi/Cargo.toml
yggdrasilwasm/Cargo.toml
yggdrasilwasm/e2e-tests/index.test.ts

Only because feature_enabled is a curse and we're moving slowly towards deprecating it. Should be safe to handle in the wasm layer for now. In practice this is only patched in tests

fix: move wasm engine to handle featureEnabled not feature_enabled

---

dotnet-engine/Yggdrasil.Engine.Tests/YggdrasilEngineTest.cs
dotnet-engine/Yggdrasil.Engine/Types.cs
dotnet-engine/Yggdrasil.Engine/Yggdrasil.Engine.csproj

Yggdrasil core has moved on from "feature_enabled" to featureEnabled. That's not publicly exposed in Edge and the SDKs can deal with it on their own terms while we migrate forward to a consistent casing scheme.
Because this affects the JSON serialising, this affects consuming SDKs as well, in practice that's just Ruby and .NET. Ruby doesn't need a patch because it already uses snake casing conversions. This brings .NET to the table

chore: fix feature enabled

---

.github/workflows/build-binaries.yaml

Adds a binary uploader for the FFI so that we can build off known artifacts for release, rather than whatever is in the source code. Also let's us reuse the code across all engines that use the FFI layer
Probably needs WASM extensions later too but this will do for now

chore: binary upload for ffi layer

---

.github/workflows/build-binaries.yaml

Does a few small things that makes the upload work correctly:
- Added a target for Windows ARM
- Set the URL rather than the release id in the upload artifact job
- Use different script for Windows/Unix for determining the tag
- ARM build for windows uses cross

fix; make binary build actually do the upload correctly

---

dotnet-engine/Yggdrasil.Engine.Tests/YggdrasilEngineTest.cs
dotnet-engine/Yggdrasil.Engine/FFI.cs
dotnet-engine/Yggdrasil.Engine/Types.cs
dotnet-engine/Yggdrasil.Engine/YggdrasilEngine.cs
ruby-engine/lib/yggdrasil_engine.rb
ruby-engine/spec/yggdrasil_engine_spec.rb
unleash-yggdrasil/src/lib.rs
yggdrasilffi/src/lib.rs
yggdrasilwasm/src/lib.rs

Adds a very simple way to list the features known to the engine at the time of calling. This is to support SDKs like .NET/Go/Java which have a current option to list the features and is typically used to iterate those features and evaluate them all. For the consuming code, this produces a list of objects that look like
{
"name" "The name of the feature toggle",
"project": "The project the feature belongs to",
"type": "Experiment, kill switch, etc, only sent if the feature response includes this, some older formats don't"
}
Currently only implemented in the FFI layers for Ruby and .NET.

feat: list known features

---

.github/workflows/build-binaries.yaml
.github/workflows/sarif-and-test.yaml
unleash-yggdrasil/src/lib.rs
unleash-yggdrasil/src/strategy_parsing.rs
unleash-yggdrasil/src/strategy_upgrade.rs
yggdrasilwasm/src/lib.rs

Sets up autoformatting
- Adds an empty rustfml.toml file, which should force most tools to use the base config for rustfmt (including cargo)
- Applies that formatting to the whole code base
- Sets up a check in the build to block unformatted cofe

chore: add autoformatting config

---

.github/workflows/publish-ruby.yaml
ruby-engine/yggdrasil-engine.gemspec

Ruby build now uses published artifacts rather than assembling from scratch. We also now just overwrite all platforms when building the gem, which lets us do this on just Ubuntu rather than a bunch of different OSes
API is stabilizing now so we're moving to 0.1.0. 1.0.0 will happen when all the SDKs have been migrated

rework ruby build to use release artifacts and disable publish

---

.github/workflows/publish-dotnet.yaml
dotnet-engine/Yggdrasil.Engine/Yggdrasil.Engine.csproj

Binary build is now handled by a completely different task that's fired on `cargo smart-release` (or just pushing a tag, but don't do that).
The .NET build now picks up the binaries from the release artifacts, and uses an internal property - YggdrasilCoreVersion in its build files to set the version of Yggdrasil FFI that will be used. This means that our versioning is now tracked in source control

chore: update build on dotnet to use release artifacts

---

.github/workflows/build-binaries.yaml

Gives us a binary for ARM-musl and x86-musl. Previously we only had a ARM-musl binary
Gives Windows binaries the name they're expected to use

chore: publish musl binaries with correct names

---

.github/workflows/build-binaries.yaml

Swaps out the Mac and Linux cargo builds for cross. Cross more widely compatible native libraries that we link against (for the Linux case, glibc, which means we work on older Debian versions).
Apparently there's no cross target for windows x86 and so we're stuck with the cargo/cross choice rather than doing everything through cross

chore: cross for more builds

---

unleash-yggdrasil/Cargo.toml
unleash-yggdrasil/src/strategy_parsing.rs

Hostname tests require an env var to be set and then unset. But Rust runs tests in parallel with no isolation... yeah
This makes those flakey tests no longer flake

fix: stop hostname tests from flaking

---

.gitignore
python-engine/build.sh
python-engine/test_unleash_engine.py
python-engine/unleash_engine.py

Brings the Python engine back to a working state and does some sanity clean ups
- Yggdrasil FFI function names have changed, this updates those to the new names
- Resolves the binary from ./lib, where it's expected to be for a production system + a build script to make that a bit easier to work with
- Adds typings to the public API
- Makes errors bubble
- Fixes a few leaks - we now free all the pointers correctly,

fix: bring python back to working state

---

python-engine/tests/test_engine.py
python-engine/yggdrasil_engine/engine.py

Adds a way for the Python engine to check whether or not a toggle has impression data enabled

feat(python): add impression data check

---

python-engine/tests/test_custom_strategy.py
python-engine/yggdrasil_engine/custom_strategy.py

This adds a little more validation to the objects passed to the register strategy hook in Python. I've put this in place because the legacy custom strategies in the Python SDK register like this:
``` python
{
"some-strategy": CustomStrategy
}
```
whereas, the Yggdrasil engine wants them like this:
``` python
{
"some-strategy": CustomStrategy()
}
```
Python is spectacularly unhelpful here, and the error message you get points out that you're missing a parameter (`self`, in this case). So this moves the check from runtime to registration time so that end users will get this pointed out in testing rather than at runtime
Apparently that's a subtle enough difference that you can lose 20 minutes debugging tests so now I'm validating in anger

feat(python): reject registration of custom strategies that don't quack like ducks

---

Cross.toml

Moves cross to build in a container that supports GLIBC 2.17 for x86, which is the requirement for manylinux2014

chore: extend compatbility to linux x86 ffi layer

---

python-engine/yggdrasil_engine/engine.py

Rename the Windows Yggdrasil DLL from `yggdrasilffi.so.dll` to `yggdrasilffi.dll`.
I think the DLL file name should be without the `.so` part on Windows.
Problem encountered with UnleashClient 6.0.1 on Windows 11 with Python 3.12.7. 
The Unleash client tries to load the file 
`<virtual environment>\Lib\site-packages\yggdrasil_engine\lib\yggdrasilffi.so.dll` 
but on the disk is 
`<virtual environment>\Lib\site-packages\yggdrasil_engine\lib\yggdrasilffi.dll`

Problem loading yggdrasilffi.dll on Windows

---

.github/workflows/publish-java.yaml
java-engine/build.gradle.kts
java-engine/gradle.properties
java-engine/src/main/java/io/getunleash/engine/YggdrasilFFI.java

So this works for the most part - packages are published to maven central with the correct binaries and name classifiers. I think some of the edge cases need more checking around loading on different architectures but I want to merge this and then iterate on it

chore: java publish

---

.github/workflows/build-dotnet.yaml
.github/workflows/build-java.yaml
.github/workflows/build-wasm.yaml
.github/workflows/sarif-and-test.yaml
README.md
dotnet-engine/Yggdrasil.Engine/FFI.cs
unleash-yggdrasil/src/lib.rs

https://linear.app/unleash/issue/2-3110/net-sdk-utf-8-scandinavian-character-issue
Adds support for flag names with valid UTF-8 characters like `ø` when running on Windows.

fix: support for utf-8 chars on win

---

unleash-yggdrasil/Cargo.toml
yggdrasilffi/Cargo.toml
yggdrasilffi/src/lib.rs
yggdrasilwasm/Cargo.toml

In order for Edge to work with deltas we need yggdrasil to also use most recent unleash-types.

chore: update to most recent unleash-types

---

.github/workflows/publish-ruby.yaml

Adds a build for Windows that works on Windows 10 and above

chore: include ruby/windows build for modern windows

---

ruby-engine/yggdrasil-engine.gemspec

Public API is about stable now. There's no plans to muck about with it too much so I think it's time this happened

chore(ruby): stable release for Ruby engine

---

unleash-yggdrasil/Cargo.toml

Bumping unleash-types from 0.15.1 to 0.15.3.

chore: bump unleash-types version

---

ruby-engine/lib/yggdrasil_engine.rb
ruby-engine/yggdrasil-engine.gemspec

Some Ruby VMs on Windows identify as x64 and not x86_64. This helps Yggdrasil correctly identify that and load the correct binary

chore(ruby): support windows arch that identifies as x64 or x86_64

---

java-engine/build.gradle.kts
java-engine/gradle.properties
java-engine/src/main/java/io/getunleash/engine/YggdrasilFFI.java

This changes the way artifact names are created for Java artifacts to be compatbile with the way [Maven OS Detector](https://github.com/trustin/os-maven-plugin) works

chore(java): rework jar publish names to be compatible with maven os detector

---

java-engine/src/main/java/io/getunleash/engine/NativeLoader.java

Does what it says on the tin. Does it the dumb way, because it looks like `Map.of` is Java 9 and above

fix(java): java engine encoding will always use UTF-8, even on Windows

---

java-engine/src/main/java/io/getunleash/engine/NativeLoader.java
java-engine/src/main/java/io/getunleash/engine/UnleashEngine.java
java-engine/src/test/java/io/getunleash/engine/UnleashEngineTest.java
unleash-yggdrasil/src/lib.rs
yggdrasilffi/src/lib.rs

Exposes the Yggdrasil version in the Java layer so we can always know what binary the Java engine is shipped with. Generally useful for other engines too

feat(java): expose core version in java engine layer

---

java-engine/gradle.properties
java-engine/src/main/java/io/getunleash/engine/CamelToSnakeMapper.java
java-engine/src/main/java/io/getunleash/engine/FeatureDef.java
java-engine/src/main/java/io/getunleash/engine/NativeLoader.java
java-engine/src/main/java/io/getunleash/engine/UnleashEngine.java
java-engine/src/main/java/io/getunleash/engine/YggResponse.java
java-engine/src/test/java/io/getunleash/engine/CamelToSnakeMapperTest.java
java-engine/src/test/java/io/getunleash/engine/UnleashEngineTest.java

This forces the Java engine to encode its strings as UTF-8 pointers rather than whatever the JVM feels like (thank you, Windows, very nice). To figure out what was going on here, there's some redesign to the way the pointers are materialized so that they bubble the Rust errors to the caller

fix(java): java engine now passes UTF-8 encoded strings correctly on Windows

---

unleash-yggdrasil/src/lib.rs

Removes an unnecessary clone, cleans up some Clippy warnings

chore: clean up some clippy warnings, remove an unnessary clone

---

.github/workflows/publish-ruby.yaml

chore: remove JRuby build support for 9.2, this isn't supported by the SDK and fails the github runners

---

java-engine/build.gradle.kts
java-engine/gradle.properties

This forces the build to pack all binaries for all platforms into a single non platform specific Jar file. Turns out that maven and gradle cannot resolve transitive dependencies correctly when they're platform specific. #sad

chore(java): move java publish to pack all binaries

---

java-engine/gradle.properties
java-engine/src/main/java/io/getunleash/engine/NativeLoader.java

The JVM does not list alpine correctly so we have to do a slightly more complex dance to resolve musl systems
This is precisely halfway between a dirty hack and very elegant

fix(java): correctly detect musl systems and load the appropriate binaries

---

.github/workflows/build-wasm.yaml
.github/workflows/sarif-and-test.yaml
ruby-engine/lib/custom_strategy.rb
ruby-engine/lib/yggdrasil_engine.rb
ruby-engine/spec/yggdrasil_engine_spec.rb
unleash-yggdrasil/benches/benchmark.rs
unleash-yggdrasil/src/lib.rs
yggdrasilffi/src/lib.rs
yggdrasilwasm/src/lib.rs

Move the check for whether the inputs to take_state are a clientFeatures object or a list of delta messages.
This is done for two reasons:
1) Consumers of take_state no longer need to know or care about what message they're handling, only that it will be handled
2) Tests can be run on the public API in Yggdrasil and that's the same public API that users will use

feat: move state ingestion entry point

---

ruby-engine/yggdrasil-engine.gemspec

Prep for release. This includes the core version that handles deltas

chore(ruby): prep for release

---

.github/workflows/publish-dotnet.yaml
dotnet-engine/Yggdrasil.Engine/FFI.cs
dotnet-engine/Yggdrasil.Engine/NativeLoader.cs
dotnet-engine/Yggdrasil.Engine/Yggdrasil.Engine.csproj
ruby-engine/yggdrasil-engine.gemspec

Add support for .NET framework.
We do this by stealing some ideas from the Java Engine - instead of using .NET core specific tools to copy the binary during the build and then load it by default we now instead dump it to the temp directory and then manually load it

fix: support dotnet framework

---

unleash-yggdrasil/src/lib.rs

A potential fix for the "start" property of the metrics bucket not being reset correctly. 
1. This change lacks tests, HELP WANTED! 
2. What is the SDK supposed to do if it is unable to send the metrics right now? (Might be solved outside of this fix)

fix: metric bucket start time should be reset everytime it is sent

---

.github/workflows/build-wasm.yaml
.github/workflows/publish-wasm.yaml
yggdrasilwasm/Cargo.toml
yggdrasilwasm/README.md
yggdrasilwasm/e2e-tests/index.test.ts

https://linear.app/unleash/issue/2-3335/create-a-publish-workflow-for-our-wasm-package
Adds the publish WASM workflow and cleans up a few things.
I wonder if we can get away with reusing our npm-release workflow. Is there a better way to test this than to just merge it and trying to publish a release?

chore: publish WASM web package

---

.github/workflows/publish-wasm.yaml

https://linear.app/unleash/issue/2-3335/create-a-publish-workflow-for-our-wasm-package
New attempt for our publish WASM package workflow.
This one uses steps from https://github.com/Unleash/.github/blob/main/.github/workflows/npm-release.yml instead of trying to use it directly. I believe the reason why it was [failing](https://github.com/Unleash/yggdrasil/actions/runs/13676066854/job/38236797932) was because we were generating the build artifacts in this job and then assuming the next one would be able to pick them up. Unless we upload the artifacts and adapt our template workflow to download them, which I would prefer not doing, that probably won't ever work. 
This new approach may be more straightforward and give us more control anyways.

chore: new publish WASM workflow attempt

---

.github/workflows/publish-javascript.yml
javascript-engine/bun.lock
javascript-engine/package.json

https://linear.app/unleash/issue/2-3336/create-a-publish-workflow-for-our-javascript-engine
This should just work, except I forgot to install dependencies before building and a few other details 🫠 
This is now correctly publishing: https://www.npmjs.com/package/@unleash/yggdrasil-engine
Workflow runs: https://github.com/Unleash/yggdrasil/actions/workflows/publish-javascript.yml

chore: fix publish javascript workflow

---

java-engine/gradle.properties
java-engine/src/main/java/io/getunleash/engine/FeatureDef.java
java-engine/src/test/java/io/getunleash/engine/UnleashEngineTest.java
unleash-yggdrasil/src/lib.rs

Exposes the environment `enabled` property for a toggle on list features. Folks on the Java SDK are asking for it back

feat(java): expose enabled on list features in core and java

---

java-engine/build.gradle.kts
java-engine/src/main/java/io/getunleash/engine/UnleashEngine.java
java-engine/src/test/java/io/getunleash/engine/UnleashEngineTest.java

Hello!
My main use case for using Unleash with the Java Client is `evaluateAllToggles()`. After migrating to the 10.x version, I was puzzled about why some of my tests kept failing. After some digging, I think I've pinpointed the issue: custom strategies aren't resolved on `getVariant()` calls, which is what `evaluateAllToggles()` uses underneath. This PR contains a fix + a test case that covers this. 
Also added a build fix for ARM-based Macs as I've had some issues running the test suite initially ("aarch64" vs "arm64" returned as architecture leading to incorrectly named native package file).
I've had a brief look at other client implementations in the repo (Ruby, C# etc.) and I _think_ the intention is to resolve custom strategies on `getVariant` as well, but that is only my …

Java: Custom strategies resolved in getVariant

---

java-engine/src/main/java/io/getunleash/engine/CustomStrategiesEvaluator.java
java-engine/src/main/java/io/getunleash/engine/UnleashEngine.java
java-engine/src/test/java/io/getunleash/engine/CustomStrategiesEvaluatorTest.java

Stops the custom strategies handler from mounting always-false custom strategies for built in strategies. In practice this isn't a problem because the Rust engine layer will simply ignore them but it does lead to some rather scary log warnings that the strategies will be disabled

fix(java): dont mount null object custom strategies for built in stategies

---

.github/workflows/build-java.yaml

Attempts to fix the java-engine build errors related to pure-was not being compiled yet

chore: fix wasm-related java-engine build failure

---

pure-wasm/src/lib.rs
unleash-yggdrasil/src/lib.rs
unleash-yggdrasil/src/state.rs
unleash-yggdrasil/src/strategy_parsing.rs
yggdrasilffi/src/lib.rs

This reworks some of the public APIs to take the EnrichedContext directly during flag evaluation. We do this so that we can sneak in a new parameter - runtime_hostname on the enriched context. That in turn we use for the hostname strategy in cases where we don't have access to IO - e.g. WASM.

fix: allow runtime hostname to be specified in context

---

java-engine/src/main/java/io/getunleash/engine/UnleashEngine.java
java-engine/src/test/java/io/getunleash/engine/LibraryTest.java
pure-wasm/src/lib.rs

Fixes the issue of passing seconds to rust which then assumes it's nanos, sends nanos back, which we then parse in as milliseconds... now it's milliseconds all the way!

chore: fix wrong usings of epoch millis/nanos

---

pure-wasm/src/lib.rs

Refactors the Rust -> Java serialization layer to use a trait for serialization. This has only one important reason for existing - the boiler plate for accessing the thread local builder, clearing the buffer and materializing the byte stream are now difficult to forget to do. That's pretty important since forgetting those things means a corrupted byte stream.
As a nice side effect, it makes the top level API much nicer, since you can do things like this
`let byte_response = SomeFlatBufferType::build_response(some_rust_struct)`
And the compiler will figure the correct dispatch thanks to monomorphization

refactor: trait for serialization

---

ruby-engine/lib/yggdrasil_engine.rb
ruby-engine/yggdrasil-engine.gemspec

Fixes a leak in the metrics handling for the Ruby engine. This was caused by the incorrect return type on the FFI function on the Ruby side.

fix(ruby): memory leak in metrics

---

java-engine/gradle.properties
java-engine/src/main/java/io/getunleash/engine/UnleashEngine.java
unleash-yggdrasil/src/lib.rs
unleash-yggdrasil/src/strategy_parsing.rs

Built in strategies are now hydrated into the engine so that it doesn't complain when it can't detect "flexibleRollout" as a built in strategy

fix(java): don't warn when using a custom strategy on built in strategies

---

java-engine/src/main/java/io/getunleash/engine/WasmInterface.java

- Multiple readers can read concurrently.
- Only one writer can write.
- When a writer wants the lock, new readers are blocked.
- Existing readers finish, then writer proceeds (no starvation).

chore: use a reentrant read write lock for better performance

---

java-engine/src/test/java/io/getunleash/engine/UnleashEngineTest.java
pure-wasm/src/lib.rs

Hi! After updating to the WASM-based Unleash Java Client 11.0.0 I've noticed a strange behaviour - all the exposure metrics collected via `getVariant` (and, by extension, `evaluateAllToggles`) were counted as a "yes" - even when the strategies resolved the toggle to not exposed. I think I got the bug - I've tweaked the `testMetrics()` case slightly to expose this case.
The changes contain:
- modified test scenario to replicate my case
- one-liner fix in the `pure_wasm` module
- some code cleanup in `UnleashEngineTest.java`

Java: fix get variant counts
